### ISSUE TITLE
Upload an artifact with single authentication token

### ISSUE THREAD

**Issue by 3jedgcm** [3jedgcm/open-artifactory#2]
Feature is to allow to use a single authentication token to upload artifacts to integrate it with other web services. 

This token would be created in the front-end and could be revoked at any time.

This token must not have an expiration date.

**Comment by 3jedgcm** [comment]
For more simplification the token must be set in GET parameter.

Exemple : `/upload?token=dba15097-3583-463a-94a5-0614867a5184`

**Comment by Ainorte** [comment]
Query parameter 'token' : takes bearer token to login
Same for Authenticator header : takes bearer token to login

API token generate one bearer to use as existing one.
Bearer token can't be regenerate !
