### ISSUE TITLE
Entry point to initialize the OTP authentication method

### ISSUE THREAD

**Issue by 3jedgcm** [3jedgcm/open-artifactory#5]
Entry point (**GET**) to retrieve a time-based **OTP**.

Must return the secret and URL, a QRCode is displayed on the frontend.

Entry point (**POST**) by sending the secret and the current valid code. 

Validate the code on the server side and save as the main **OTP**. 

Optional: Also returns a jwt token for authentication.

From this moment on these methods return a **403** error to explain OTP is already set.

**Comment by Ainorte** [comment]
`Entry point (GET) to retrieve a time-based OTP.`

Prefer a POST method to hide it for end user
